name: masterstudy_app
description: MasterStudy App by Stylemix

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.2.5+65

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  #networking
  http: ^0.13.4
  dio: ^4.0.6
  rxdart: ^0.27.3
  get_it: ^7.2.0

  #stateManagement
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  #di
  inject:
    path: ./inject.dart/package/inject

  #utils
  meta: ^1.1.6
  equatable: ^2.0.5
  json_annotation: ^4.4.0
  share_plus: ^6.3.1
  package_info_plus: ^3.0.3
  device_info_plus: ^8.1.0
  overlay_support: ^2.1.0
  image_downloader: ^0.31.0
  intl: ^0.17.0
  flutter_inappwebview: ^5.7.2+3

  #googleSignIn
  google_sign_in: ^6.0.2

  #facebookSignIn
  flutter_facebook_auth: ^5.0.7

  #utils
  shared_preferences: ^2.0.15
  path_provider: ^2.0.11
  webview_flutter: ^2.0.4
  connectivity_plus: ^3.0.3
  external_path: ^1.0.1

  #Firebase
  firebase_crashlytics: ^3.0.11
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1

  #ui
  cupertino_icons: ^1.0.3
  google_fonts: ^2.3.1
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.5
  shimmer: 2.0.0
  image_picker: ^0.8.4+11
  transparent_image: ^2.0.1
  flutter_staggered_grid_view: ^0.6.1
  flutter_html: 3.0.0-alpha.6
  file_picker: ^5.2.5
  video_player: ^2.3.0
  chewie: ^1.0.0
  font_awesome_flutter: ^10.3.0
  youtube_player_flutter: ^8.0.0
  vimeo_player_flutter: ^0.0.3+1
  url_launcher: ^6.0.20
  cached_network_image: ^3.2.0
  html_unescape: ^2.0.0
  page_transition: ^2.0.9
  in_app_purchase: ^3.0.8
  image: ^3.1.3
  fluttertoast: ^8.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7

  json_serializable: ^6.1.4

  inject_generator:
    path: ./inject.dart/package/inject_generator

flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/raster/
    - assets/images/vector/
    - assets/localization/
